### ISSUE TITLE
Leave messages are not working properly

### ISSUE THREAD

**Issue by crimenoodle** [crimenoodle/WildAnarchy#1]
leave messages are not working correctly.

we need to look into the WildAnarchyUtility plugin's join/leave manager and see what's causing the issue, or just remove the functionality for now.

**Comment by sleepylessons** [comment]
This has been fixed as I've removed all logic related to joins/leaves in WildAnarchyUtility, except for the original welcome message that new & returning players receive upon login.

We will implement a new solution for join/leave message ignoring/limiting.
