### ISSUE TITLE
Jesus kicks you for flying

### ISSUE THREAD

**Issue by DaK1ing** [crimenoodle/WildAnarchy#34]
**Describe the bug**
When you standing in water for more than 7 sec it’s you for flying and also when you your walking or speeding on water after around 6-8 seconds it lags you back and then kicks for flying
**To Reproduce**
- place a block under or turn Jesus off then back on is what I’ve done

**Expected behavior**
A clear and concise description of what you expected to happen. I feel it should be fixed and could also help out the whole server in a way (this was also a problem on NA)

**Screenshots**
If applicable, add screenshots to help explain your problem. I’m not at my pc at the moment, but I’ll try and post some when I’m available on my pc

**Additional context**
Was a problem on NA too

**Comment by sleepylessons** [comment]
I've enabled a perm that should allow you to use waterwalk/jesus

It seems to work pretty well for me and other people on the server have confirmed. I'm closing this now @DaK1ing, feel free to comment back here if it's still not working for you.
